name: csharp-api

on:
  push:
    branches: main
    paths:
     - apps/csharp-api/*
     - .github/workflows/csharp-api.yml
  pull_request:
    branches: main

jobs:
  push-to-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./apps/csharp-api
          push: true
          tags: ghcr.io/jimpaine/containerapp:csharp-api-0.1.${{ github.RUN_NUMBER }}
  deploy-app:
    runs-on: ubuntu-latest
    needs: push-to-packages
    steps:
      - uses: actions/checkout@v2
      - run: |
          az login --service-principal \
          -u ${{ secrets.AZ_CLI_APP_ID }} \
          -p ${{ secrets.AZ_CLI_PASSWORD }} \
          --tenant ${{ secrets.AZ_CLI_TENANT_ID }}
      - run: az account set -s ${{ secrets.AZ_CLI_SUBSCRIPTION }}
      - run: |
          az deployment group create \
          -n 'csharp-api${{ github.RUN_NUMBER }}' \
          -g  rg-containerapps-3wl63cg4lbi4o \
          -f ./apps/csharp-api/main.bicep \
          -p environmentName=environment image=ghcr.io/jimpaine/containerapp:csharp-api-0.1.${{ github.RUN_NUMBER }}